# Generated by Django 4.1.4 on 2023-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='testscore',
            new_name='testscore1',
        ),
        migrations.AddField(
            model_name='student',
            name='testscore2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='testscore3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='testscore4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='testscore5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='testscore6',
            field=models.FloatField(default=0),
        ),
    ]
